### PR TITLE
Have the code comply with PSR-2

### PR DESCRIPTION
**Pull request by schinkel**
I feel very sorry that my pull request broke the build. I fixed the code to comply with PSR-2 guidelines so that the build should pass again. Again, sorry.

### CODE REVIEW

**Comment by DianeD** [comment]
Thanks @schinkel ! Can you please sign the CLA (link above)? Also, you should delete the registered app with that client ID.

**Comment by schinkel** [comment]
Wow, thank you @DianeD. I am kinda new with this.

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by DianeD** [comment]
Thanks again, @schinkel !

**Pull request merged**
